### ISSUE TITLE
嗨，你那边GC 抑制已经在线上ABTest了吗？

### ISSUE THREAD

**Issue by Edison0716** [PTrainbow/GcJitDelay#1]

**Comment by PTrainbow** [comment]
是的，但是并没有明显收益···
现在打算 Android 10 以后的版本不开启 GC 抑制了，具体抖音是什么策略我也不太清楚
而且 inlinehook 全量开了以后，线上也有一些 crash

**Comment by Edison0716** [comment]
针对 线程栈 1MB 的精简 你们有做吗？

**Comment by Edison0716** [comment]
> 

Android 10 版本 本身系统会进行 2-3 秒的延迟GC吧。主要是 Android 5.0 - Android 9.0 的机器是否有收益？

**Comment by PTrainbow** [comment]
> 针对 线程栈 1MB 的精简 你们有做吗？

有做

**Comment by PTrainbow** [comment]
> > 
> 
> Android 10 以上的版本 本身系统会进行 2-3 秒的延迟GC吧。主要是 Android 5.0 - Android 9.0 的机器是否有收益？

是的，所以现在修改了策略，还在等版本放量。

**Comment by Edison0716** [comment]
有结论了吗
