### ISSUE TITLE
Android 6.0 Vivo GC inline hook 失败

### ISSUE THREAD

**Issue by Edison0716** [PTrainbow/GcJitDelay#2]
![image](https://github.com/PTrainbow/GcJitDelay/assets/8669094/8f4214af-ed93-4cf9-beeb-1b536b957442)

**Comment by PTrainbow** [comment]
> ![image](https://user-images.githubusercontent.com/8669094/252883290-8f4214af-ed93-4cf9-beeb-1b536b957442.png)

可能有机型适配问题？之前测试使用的机器 Android 6.0 应该是可以的
