### ISSUE TITLE
find_package时序问题

### ISSUE THREAD

**Issue by xixiwai0819** [PTrainbow/GcJitDelay#3]
CMakeLists.txt中find_package(shadowhook REQUIRED CONFIG)需要放在project("art")下方，否则编译不过

**Comment by PTrainbow** [comment]
> CMakeLists.txt中find_package(shadowhook REQUIRED CONFIG)需要放在project("art")下方，否则编译不过

奥，确实

https://github.com/PTrainbow/GcJitDelay/pull/4

修复了
